import { INVALID } from "zod/v3";

// src/utils/errorCodes.js
export const ErrorCodes = Object.freeze({
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_INPUT: "INVALID_INPUT",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  Mail_ERROR: "MAIL_SENDING_ERROR",
  INVALID_EMAIL: "INVALID_MAIL",
  AUTH_REQUIRED: " AUTHENTICATION_REQUIRED",
  RESET_TOKEN_EXPIRED: "RESET_TOKEN_EXPIRED",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  LINK_NOT_FOUND:"LINK_NOT_FOUND"
  // Add more as needed;
});
